site_name: 'Terraformで構築するAWS'

theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  highlightjs: true
  hljs_languages:
    - 'yaml'
    - 'dockerfile'
    - 'ruby'

extra:
  search:
    language: 'jp'

markdown_extensions:
  - 'admonition'
  - 'footnotes'
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - 'assets/custom.css'

extra_javascript:
  - 'assets/custom.js'

nav:
  - 'Home': 'index.md'
  - 'はじめてのTerraform':
      - 'Terraformとは': 'first/about.md'
      - '環境を準備する': 'first/preparation.md'
      - 'とりあえず触ってみる': 'first/handson.md'
  - 'ハンズオン':
      - '概要': 'handson/about.md'
      - 'VPC': 'handson/vpc.md'
      - 'ALB': 'handson/alb.md'
      - 'ECS': 'handson/ecs.md'
      - 'https化': 'handson/https.md'
      - 'シンタックスの活用': 'handson/syntax.md'
  - 'laravelを動かす':
      - '概要': 'laravel/about.md'
      - 'docker-composeの起動': 'laravel/docker-compose.md'
      - 'RDS': 'laravel/rds.md'
      - 'ECR': 'laravel/ecr.md'
      - 'ECS': 'laravel/ecs.md'
      - '片付け': 'laravel/cleanup.md'
  # - 'おまけ':
  #     - '変数を使用する': 'variable.md'
  #     - 'ファイルの分割': 'module.md'
  #     - '設定情報をAWSへ格納': 'handson/aurora.md'
  #     - 'オートスケール': 'handson/cleanup.md'
  #     - 'CI/CD': 'handson/cleanup.md'
  # - 'Next Step': 'next-step.md'
